spring:
  rabbitmq:
    port: 5672
    host: 192.168.99.100
    username: user
    password: pass

galatos:
  rabbitmq:
    key: payments.created
    exchange:
      durable: true
      type: topic
      value: payments
    queue:
      value: payments.created
      durable: true